name: Build and Deploy

on:
  push:
    branches:
      - dev # 'believeme' 브랜치에 푸시할 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v2

      # 2. Node.js 설치
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 필요한 Node.js 버전으로 수정

      # 3. 의존성 설치 및 빌드
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # 4. deploy 브랜치 체크아웃
      - name: Checkout deploy branch
        run: |
          # 사용자 정보 설정
          git config --global user.name "pleasebelieveme"  # 사용자 이름
          git config --global user.email "cain1227@naver.com"  # 사용자 이메일

          # 'deploy' 브랜치 체크아웃, 없으면 새로 생성
          git checkout deploy || git checkout --orphan deploy
          git rm -rf .  # deploy 브랜치의 기존 파일 삭제

      # 5. 빌드 파일 복사
      - name: Copy build files
        run: |
          cp -r build/* .
          rm -rf build

      # 6. 변경 사항이 있는 경우에만 커밋
      - name: Commit and push if there are changes
        run: |
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Deploy React build files"
            git push origin deploy --force
          else
            echo "No changes to commit"
          fi